server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: false
zuul:
  # Basically just removes the Authorization from the defaults,
  # since we are not using zuul as the auth termination and want
  # independent services to handle auth.
  sensitive-headers: Cookie,Set-Cookie